### PR TITLE
Fix security issue concerning links in mark down

### LINKED ISSUE #235: Fix security issue concerning links in mark down

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #235

### CODE REVIEW

File: src/renderer/components/misc/MarkDown.vue [hunk 1]
```diff
@@ -26,7 +26,6 @@ marked.use({
 const allowedTags = ["p", "em", "b", "strong", "ul", "ol", "li", "code", "pre", "blockquote", "span", "del", "body"];
 
 const allowedAttributes: string[] = [];
-
 if (props.allowLinks) {
     allowedTags.push("a");
```
Comment (1-alex98) [inline src/renderer/components/misc/MarkDown.vue:31]: I tried sanitizing the link. Till I realized that it does not help at all since all the other stuff is not sanitized. And all the other functions no not sanitize their stuff...

Comment (1-alex98) [reply src/renderer/components/misc/MarkDown.vue:31]: With this will-navigate is the only line of defense

**Comment by 1-alex98** [comment]
I gotta get this to run in IntelliJ. I really do not know how to use git in VSCode XD
