### PR TITLE
Fix replay cache issue

### LINKED ISSUE #332: Replay parsing triggered on new-in progress game.
New replay file is created as soon as engine starts up, it's empty, and it's filled up as the game progresses. Looks like currently lobby tries to parse replay as soon as the engine starts up which results in error and the new replay file is deleted! Both of those things are unintended, moreover, I don't think we should ever just remove demo files if we fail to parse them.

<details>
<summary>Log</summary>

```
[19:04:53.854] DEBUG: replay-content.ts - Chokidar -=- Replay added: /home/p2004a/.local/share/Beyond All Reason/demos/2025-03-23_18-04-51-841_Wanderlust 2_2025.01.6.sdfz
[19:04:53.855] DEBUG: replay-content.ts - Caching: /home/p2004a/.local/share/Beyond All Reason/demos/2025-03-23_18-04-51-841_Wanderlust 2_2025.01.6.sdfz
[19:04:53.859] ERROR: replay-content.ts - Error caching replay: /home/p2004a/.local/share/Beyond All Reason/demos/2025-03-23_18-04-51-841_Wanderlust 2_2025.01.6.sdfz
[19:04:53.859] ERROR: replay-content.ts - unexpected end of file
    err: {
      "type": "Error",
      "message": "unexpected end of file",
      "stack":
          Error: unexpected end of file
              at genericNodeError (node:internal/errors:983:15)
              at wrappedFn (node:internal/errors:537:14)
              at Zlib.zlibOnError [as onerror] (node:zlib:185:17)
    }
Error: unexpected end of file
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at Zlib.zlibOnError [as onerror] (node:zlib:185:17) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
[19:04:53.961] DEBUG: replay-content.ts - Chokidar -=- Replay removed: /home/p2004a/.local/share/Beyond All Reason/demos/2025-03-23_18-04-51-841_Wanderlust 2_2025.01.6.sdfz
```

</details>

### PR DESCRIPTION
**Pull request by JasonReed-2**
Fixes #332 by queuing the replay files to be cached only after the game closes.

### CODE REVIEW

File: src/main/content/replays/replay-content.ts [hunk 1]
```diff
@@ -84,7 +86,11 @@ export class ReplayContentAPI {
         }
     }
 
-    protected async cacheReplay(replayFilePath: string) {
+    protected async cacheReplay(replayFilePath: string, obj: ReplayContentAPI) {
```
Comment (p2004a) [inline src/main/content/replays/replay-content.ts:89]: I don't understand why you are passing `obj`, the arrow function captures `this` from outer scope

[Quoting MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this):

> [Arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) differ in their handling of this: they inherit this from the parent scope at the time they are defined. This behavior makes arrow functions particularly useful for callbacks and preserving context

inside of `this.cacheReplay(filePath, this)` invocation `obj == this`.

File: src/main/content/replays/replay-content.ts [hunk 2]
```diff
@@ -84,7 +86,11 @@ export class ReplayContentAPI {
...
+        // Don't try to cache an empty replay file
+        const stat = await fsPromises.stat(replayFilePath);
+        if (stat.size === 0) return;
```
Comment (p2004a) [inline src/main/content/replays/replay-content.ts:92]: We skip file size if it's 0:
- Will this file caching be re-triggered once the engine finishes running?
- There is still race condition here of engine writing a few bytes but still not full header and this won't be parsable

**Review by p2004a — COMMENTED** [review]
One more thing I highlight in that issue that lobby shouldn't really remove those under any circumstance and leave that to the user, do you have a good reason to keep the deletion?

File: src/main/content/replays/replay-content.ts (hunk 1 above)
Comment (JasonReed-2) [reply src/main/content/replays/replay-content.ts:89]: Right but cacheReplay is not an arrow function. Now that I think on this more: making that change was probably the right decision. I'll update that.

**Comment by bcdrme** [comment]
I doesn't crash but it doesn't parse the replay either. I had to restart the app (or hit F5) to get the replay parsing running for a game I started and stopped.

File: src/main/content/replays/replay-content.ts (hunk 1 above)
Comment (p2004a) [reply src/main/content/replays/replay-content.ts:89]: All calls to `cacheReplay` are via `this.cacheReplay`, the `this` inside of the method should be properly bound, so `obj == this`.

Comment (JasonReed-2) [reply src/main/content/replays/replay-content.ts:89]: Gotcha. I was encountering an error with "this" being undefined when I was testing. That is what led me to this change. I'll set it back and give it another test.

**Comment by JasonReed-2** [comment]
I can update to remove the rename action to avoid "deleting" the replay file if it couldn't be cached.

I think I need a better understanding of the desired outcome.

Should the replay be continuously parsed and cached as the .sdfz file is being written to by the engine?
If not: is it sufficient to cache the generated replay files only after the game closes?

**Comment by bcdrme** [comment]
Sure. 

A replay is an archive containing a bunch of files. We want to extract metadata from theses, this is the "caching" part. 
When you start a game and stop it, a new .sdfz file should have been generated and needs parsing. This used to work on detecting a new .sdfz file in the replay dir. 
The same mechanism is used when downloading and dropping a file in the replay dir (chokidar).

Now you could just start a scan of new files to "cache" after a game quit event, that would be a way of doing it. Or ask for a game engine change, so the engine generates a `.sdfz.tmp` until it's complete, then renames to `.sdfz` when the file is writter fully.

**Comment by p2004a** [comment]
IMHO, easiest would be to pause all replay parsing while there is engine instance running, and resume when engine is stopped. When engine is running, nobody should be trying to start some replay anyway.

**Comment by JasonReed-2** [comment]
Thanks for the feedback and suggestions @p2004a & @bcdrme. I made the update to queue the replay files to be cached and cache them after the game closes.

**Review by bcdrme — CHANGES_REQUESTED** [review]
1. Downloading a replay and dropping it in the `demos` folder doesn't trigger a parsing. This is a regression, this is why this folder was watched by chokidar.

2. After watching a replay, the game closes, it scans all the files again. This is more minor, but some people will have hundreds of files in their `demos` folder.

File: src/main/content/replays/replay-content.ts [hunk 3]
```diff
@@ -84,7 +84,13 @@ export class ReplayContentAPI {
         }
     }
 
-    protected async cacheReplay(replayFilePath: string) {
+    cacheReplay = async (replayFilePath: string) => {
```
Comment (p2004a) [inline src/main/content/replays/replay-content.ts:87]: Why make this change? Why not keep it `protected async cacheReplay` ?

Comment (p2004a) [reply src/main/content/replays/replay-content.ts:87]: The only place where I see usage of this is incorrect is above

```js
.forEach(this.cacheReplay);
```

It needs to be

```js
.forEach((file) => this.cacheReplay(file));
```

instead.

That's a bug in that line, not here.

Comment (JasonReed-2) [reply src/main/content/replays/replay-content.ts]: Made an update for this. Thank you!

**Comment by JasonReed-2** [comment]
Sorry for the amount of back and forth on this. Next time: I'll do better to understand the feature and ask clarifying questions before jumping into a solution.

**Comment by p2004a** [comment]
No worries :D! Thanks a lot for this fix!

**Review by p2004a — APPROVED** [review]
